# Site Settings
title: CB Media Group
email: cb-mediagroup@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "https://cb-media.github.io"
url: "https://cb-media.github.io"
twitter_username: cb-mediagroup
github_username:  cb-mediagroup
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM